@HotelListingApi_HostAddress = https://localhost:7274

POST {{HotelListingApi_HostAddress}}/api/countries
Content-Type: application/json

{
  "name": "Testcountry8",
  "shortName": "TC8"
}

###

GET {{HotelListingApi_HostAddress}}/api/countries

###

@id=6
GET {{HotelListingApi_HostAddress}}/api/countries/{{id}}

###

PUT {{HotelListingApi_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{
  "id": 3,
  "name": "India",
  "shortName": "IND"
}

###

DELETE {{HotelListingApi_HostAddress}}/api/countries/{{id}}

###

##########################################################################


POST {{HotelListingApi_HostAddress}}/api/hotels
Content-Type: application/json

{
  "name": "Hotel F",
  "address": "123098 Main St",
  "rating": 4.5,
  "countryId": 3
}

###

GET {{HotelListingApi_HostAddress}}/api/hotels

###

GET {{HotelListingApi_HostAddress}}/api/hotels/{{id}}

###

PUT {{HotelListingApi_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  "id": 6,
  "name": "Hotel K",
  "address": "it is somewhere",
  "rating": 4.5,
  "countryId": 2
}

###

DELETE {{HotelListingApi_HostAddress}}/api/hotels/{{id}}

###
