@HotelListingApi_HostAddress = https://localhost:7274
@apiKey=dXNlcjRAbG9jYWxob3N0LmNvbTpQYXNzd29yZEAxMjM=
POST {{HotelListingApi_HostAddress}}/api/countries
Content-Type: application/json

{
  "name": "Testcountry8",
  "shortName": "TC8"
}

###

GET {{HotelListingApi_HostAddress}}/api/countries
#X-Api-Key: {{apiKey}}
#Authorization: Basic dXNlcjRAbG9jYWxob3N0LmNvbTpQYXNzd29yZEAxMjM=
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0Yzg2Zjk1MC1lODAxLTQzODUtYjlmNC1mODJhYjQwOWZmYWEiLCJlbWFpbCI6InVzZXI0QGxvY2FsaG9zdC5jb20iLCJqdGkiOiIxNGI5ZTZkZi1hNjZiLTQ1NGMtYWEwZi1jZjhjN2Q3NzFhNTUiLCJuYW1lIjoiTGFzdCwgRmlyc3QiLCJleHAiOjE3ODI2MTc5NDMsImlzcyI6IkhvdGVsTGlzdGluZ0FwaSIsImF1ZCI6IkhvdGVsTGlzdGluZ0FQSUNsaWVudCJ9.YtZRDhjTbNHkJ43bSKeeIrEuKCKELDhfj5hRJLLYGgk

###

@id=6
GET {{HotelListingApi_HostAddress}}/api/countries/{{id}}

###

PUT {{HotelListingApi_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{
  "id": 3,
  "name": "India",
  "shortName": "IND"
}

###

DELETE {{HotelListingApi_HostAddress}}/api/countries/{{id}}

###

##########################################################################


POST {{HotelListingApi_HostAddress}}/api/hotels
Content-Type: application/json

{
  "name": "Hotel F",
  "address": "123098 Main St",
  "rating": 4.5,
  "countryId": 3
}

###

GET {{HotelListingApi_HostAddress}}/api/hotels

###

GET {{HotelListingApi_HostAddress}}/api/hotels/{{id}}

###

PUT {{HotelListingApi_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  "id": 6,
  "name": "Hotel K",
  "address": "it is somewhere",
  "rating": 4.5,
  "countryId": 2
}

###

DELETE {{HotelListingApi_HostAddress}}/api/hotels/{{id}}

###



POST {{HotelListingApi_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "user4@localhost.com",
  "password": "Password@123",
  "firstName": "First",
  "LastName": "Last"
}

###

POST {{HotelListingApi_HostAddress}}/api/auth/Login
Content-Type: application/json

{
  "email": "user4@localhost.com",
  "password": "Password@123"
}

###
